lsi: false
safe: true
source: ["./"]
remote_theme: just-the-docs/just-the-docs
incremental: true
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
