permalink: /:collection/:year-:month-:day-:title:output_ext
lsi: false
safe: true
source: ["./"]
remote_theme: just-the-docs/just-the-docs
incremental: true
timezone: Europe/Prague
highlighter: rouge
color_scheme: dark
show_dir_listing: true
layout: default
nav_order: 4
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
